## STAGE 1: Build ###
FROM node:18.17.1-alpine AS build
ENV HOME=/usr/local/app
ENV DIST_PATH=/app/apps
## start building backend
WORKDIR ${HOME}
COPY ./ ${HOME}
RUN npm install --force
RUN npm run build:api
# COPY /usr/local/app/dist/apps/api ${DIST_PATH}}
EXPOSE 4444
## STAGE 2: Run ###
CMD ["node", "api/main"]